import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
//useQuery used for graphql
import { useQuery } from '@apollo/client';

import QUERY_TESTUSER from './testUserQuery.graphql';
import QUERY_COUNTRIES from './queryCountries.graphql';

import styles from '../styles/Home.module.css';



const Home: NextPage = () => {
  const { data, loading, error } = useQuery(QUERY_TESTUSER);

  //check for errors
  if (error) {
    return <p>: an error happened</p>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Trying out NextJS TypeScript GraphQl</title>
        <meta name="version1.0" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Lets grab some stuff with GraphQL</h1>
      <div>
        <h3>stuff will go here</h3>
      </div>

      <div>
      <h1>Please Login Here </h1>
      <div></div>
      </div>

      <h1> TestUsers </h1>
      {/* let the user know we are fetching testUsers */}
      {loading && <p>loading...</p>}
      <div>
        {/* had error without ? ...could not read property 'countries' of undefined*/}
        {data?.testUser?.map((user: { name: string, address: string }) => (
          <div key={user.name}>{user.name}: {user.address}</div>
        ))}
      </div>

    </div>
  )
}

export default Home
