import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
//useQuery used for graphql
import { useQuery, useMutation } from '@apollo/client'; //state management library for remote and local data with graphql

import withApollo from '../lib/nextapollo';
import QUERY_TESTUSER from './testUserQuery.graphql';
import QUERY_COUNTRIES from './queryCountries.graphql';
import MUTATION_TESTUSER from './api/graphql/testMutation.graphql';

import styles from '../styles/Home.module.css';
import Link from 'next/link';

import AddUser from '../components/AddUser';


const Home: NextPage = (props) => {
  //const data = [];
  const { data, loading, error } = useQuery(QUERY_TESTUSER);
  //const { dataA,  } = useMutation(MUTATION_TESTUSER);

  //check for errors
  if (error) {
    return <p>: an error happened</p>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Trying out NextJS TypeScript GraphQl</title>
        <meta name="version1.0" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Lets grab some stuff with GraphQL</h1>
      <div>
        <h3>stuff will go here</h3>
      </div>

      <div>
      <Link href="/login">
        <h1>Please Login Here </h1>
      </Link>
      <div></div>
      </div>

      <h1> TestUsers </h1>
      {/* let the user know we are fetching testUsers */}
      {loading && <p>loading...</p>}
      <div>
        {/* had error without ? ...could not read property 'countries' of undefined*/}
        {data?.testUser?.map((user: { name: string, address: string, _id: string }) => (
          <div key={user.name}>{user.name}: {user.address} {user._id}</div>
        ))}
      </div>

      <AddUser />

    </div>
  )
}

export default Home;
//xport default withApollo({ ssr: true})(Home);
